name: deploy-to-gh-pages

on:
  push:
    branches:  master
    
jobs:
  download-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
    - run: git config --global user.email "dmitriy_aleshin_00@mail.ru"
    - run: git config --global user.name "KoTuK2306"
    - uses: actions/setup-node@v3
    - run: npm ci
    
  run-deploy: 
    runs-on: ubuntu-latest
    needs: [download-dependencies]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' 
    - run: npm run deploy
